spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Checking;encrypt=false;trustServerCertificate=true
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE